### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Salbei** [VanessaE/pipeworks#101]
Hi,
I have an error from this very useful mod:

22:58:45: ERROR[main]: ERROR: An unhandled exception occurred: .../minetest/.minetest/mods/pipeworks/flowing_logic.lua:81: bad argument #1 to 'get_node' (table expected, got nil)
22:58:45: ERROR[main]: stack traceback:
22:58:45: ERROR[main]:  [C]: in function 'get_node'
22:58:45: ERROR[main]:  .../minetest/.minetest/mods/pipeworks/flowing_logic.lua:81: in function 'spigot_check'
22:58:45: ERROR[main]:  /home/minetest/.minetest/mods/pipeworks/pipes.lua:210: in function </home/minetest/.minetest/mods/pipeworks/pipes.lua:209>

**Comment by VanessaE** [comment]
Fixed with the merge of new_flow_logic branch.
