### ISSUE TITLE
Feature Request: Support planting by Deployer

### ISSUE THREAD

**Issue by lightonflux** [VanessaE/pipeworks#106]
One thing i thing MT can't provide (afaik) are farming machines. 

If the deployer or a new / other block could plant seeds we would be a step nearer to automatic farming.

**Comment by est31** [comment]
You actually can plant with a deployer. Just place it below the farm node, facing up.

**Comment by t4im** [comment]
This is actually what e8ab36a attempted to fix… but i had to revert it with ac4f761, because it messed up wielder setups in general. It won't fix so soon without a smaller rewrite of wielder behavior.

**Comment by thatgraemeguy** [comment]
To plant seeds you need to place the deployer below the node to plant on, facing up. For some reason, planting saplings works just fine with the deployer above and adjacent to the node being planted on.

**Comment by t4im** [comment]
That's because seeds check for the farmed-dirt with `pointed_thing.below` within a callback function while saps don't and are simply placed where the deployer points at.  Due to the switch (as you can see in the linked commits) that `below` happens to be the first node, instead as expected the one following the first one. Additionally it checks for seeds being placed _on top_ via coordinates, which is why that position is the only one working.

**Comment by lightonflux** [comment]
>  because it messed up wielder setups in general

I noticed. It crashes with the current git. 

Planting works as described. \o/

**Comment by t4im** [comment]
_current_ git should not crash! This was already reverted in a followup commit, so the crash is probably unrelated. Could you paste the stacktrace?

**Comment by lightonflux** [comment]
13:43:56: ACTION[ServerThread]: singleplayer places node mesecons_button:button_off at (-40,1,149)
        13:43:56: ACTION[ServerThread]: facedir: 0
        13:43:57: ACTION[ServerThread]: singleplayer places node mesecons_button:button_off at (-40,1,148)
        13:43:57: ACTION[ServerThread]: facedir: 0
        13:43:58: ACTION[ServerThread]: singleplayer digs mesecons_button:button_on at (-40,1,148)
        13:43:59: ACTION[ServerThread]: singleplayer digs default:chest at (-39,2,150)
        13:43:59: ERROR[main]: ServerError: /home/lightonflux/.minetest-dev/bin/../mods/invtweak/init.lua:275: attempt to compare number with nil
        13:43:59: ERROR[main]: stack traceback:
        13:43:59: ERROR[main]: 	/home/lightonflux/.minetest-dev/bin/../mods/invtweak/init.lua:275: in function 'callback'
        13:43:59: ERROR[main]: 	/home/lightonflux/.minetest-dev/bin/../builtin/game/item.lua:485: in function 'on_dig'
        13:43:59: ERROR[main]: 	...e/lightonflux/.minetest-dev/bin/../mods/pipeworks/wielder.lua:334: in function 'act'
        13:43:59: ERROR[main]: 	...e/lightonflux/.minetest-dev/bin/../mods/pipeworks/wielder.lua:109: in function 'wielder_on'
        13:43:59: ERROR[main]: 	...e/lightonflux/.minetest-dev/bin/../mods/pipeworks/wielder.lua:145: in function 'action_on'
        13:43:59: ERROR[main]: 	....minetest-dev/bin/../mods/mesecons/mesecons/internal.lua:189: in function <....minetest-dev/bin/../mods/mesecons/mesecons/internal.lua:184>
        13:43:59: ERROR[main]: 	...netest-dev/bin/../mods/mesecons/mesecons/actionqueue.lua:90: in function 'execute'
        13:43:59: ERROR[main]: 	...netest-dev/bin/../mods/mesecons/mesecons/actionqueue.lua:84: in function <...netest-dev/bin/../mods/mesecons/mesecons/actionqueue.lua:61>
        13:43:59: ERROR[main]: 	/home/lightonflux/.minetest-dev/bin/../builtin/game/register.lua:341: in function </home/lightonflux/.minetest-dev/bin/../builtin/game/register.lua:329>
        AL lib: (WW) FreeContext: (0x39004d0) Deleting 2 Source(s)
        AL lib: (WW) FreeDevice: (0x33877e0) Deleting 117 Buffer(s)
        13:44:12: ERROR[main]: mod "wings" has unsatisfied dependencies:  "playereffects"
        13:44:12: ERROR[main]: The following mods could not be found: "mesecons_compatibility"
        [OK] Mesecons
        Pipeworks loaded!
