### ISSUE TITLE
Support for connected chests

### ISSUE THREAD

**Issue by lightonflux** [VanessaE/pipeworks#108]
It would be awesome if pipeworks would support connected chests. At the moment the content of a pipe get's dropped on top of the wide chest instead of put in it.

**Comment by VanessaE** [comment]
What is a connected chest?  I am not aware of such a thing in the default game.

**Comment by lightonflux** [comment]
Oh sorry.

You are right it is not part of the default game (yet) but a external mod.

→ https://forum.minetest.net/viewtopic.php?f=9&t=10264#p156571

**Comment by asl97** [comment]
@lightonflux you got it the wrong way round, since it is a mod, they should be the one to add support instead of this mod supporting it.

post a issue at https://github.com/HybridDog/connected_chests

ps: it's the same thing with technic
