### ISSUE TITLE
Scale overlay texture

### ISSUE THREAD

**Issue by lightonflux** [VanessaE/pipeworks#113]
If you use higher res texture packs the holes in chests are not centred. 

Pipeworks should centre the overlay texture to work with all TP resolutions. 

![auswahl_105](https://cloud.githubusercontent.com/assets/1377943/6993225/ed67decc-daed-11e4-89ac-055f397fb9d7.png)

**Comment by VanessaE** [comment]
This is an engine fault, not pipeworks.  The engine does not scale or center overlaid images if the resolutions differ, and there's no way for the mod to detect the user's texture pack to adjust for this.
