### ISSUE TITLE
Steam turbines don't connect to pipes under them

### ISSUE THREAD

**Issue by HybridDog** [VanessaE/pipeworks#118]
How can l make them become connected on their bottom?
![screenshot_20150827_144748](https://cloud.githubusercontent.com/assets/3192173/9520837/dcd615b6-4cca-11e5-986d-967354486d99.png)

l think the particlespawner doesn't work correctly, when l e.g. set its minp.x to maxp.x, their difference seems to be -1 anyhow

https://github.com/HybridDog/technic_extras/blob/master/init.lua#L319

**Comment by thatgraemeguy** [comment]
~~Since when is technic:steam_turbine even a thing?~~

https://github.com/HybridDog/technic_extras/blob/master/init.lua

**Comment by asl97** [comment]
@HybridDog i don't see the tube arg in the register_node

see https://github.com/VanessaE/pipeworks/blob/master/trashcan.lua#L13 as an example

also, this belong on [technic_extras issue tracker](https://github.com/HybridDog/technic_extras/issues)

you could CC other people if they are related to the issue and they would get a notification if they didn't block it using `@`, for example @VanessaE

**Comment by HybridDog** [comment]
>see https://github.com/VanessaE/pipeworks/blob/master/trashcan.lua#L13 as an example, namely the connect_sides.

but l want to make it connect to pipes, not to tubes

**Comment by asl97** [comment]
ah, pipes...

please ignore my comment, i thought they use the same thing as tubes....

i just notice is still hard coded in the new_flow_logic branch as well...

**Comment by t4im** [comment]
Yes, but you have to add the pipe group and
```lua
	after_place_node = function(pos)
		pipeworks.scan_for_pipe_objects(pos)
	end,
	after_dig_node = function(pos)
		pipeworks.scan_for_pipe_objects(pos)
	end,
```
To actually make pipes around that position look for pipe devices.

`on_destruct` as you use for scanning is for example too late, as the node is still there, and will be found (thus you need to scan after the removal).
I _think_ `on_construct` might be too early in the node lifecycle, despite the api claim, that the node was already set. Perhaps it's simply not ready enough to be found yet.

There is also a \#minetest-technic channel on freenode to get support with pipeworks related questions.

**Comment by asl97** [comment]
@t4im there isn't any pipe group, it is hard coded to look for `pipeworks:pipe_`

https://github.com/VanessaE/pipeworks/blob/new_flow_logic/autoplace_pipes.lua#L7

**Comment by t4im** [comment]
Ah, there we go. There is a pipe group, but it isn't used. Now that's something fixable. Provided @VanessaE wants pipe connections to become public api already before the new_flow_logic has been done.

**Comment by VanessaE** [comment]
All new pipe-related (not tube-related) code should go only into the new_flow_logic branch.  The only reason that branch has not been merged to master (permanently, that is :stuck_out_tongue_closed_eyes: ) is because some folks feel it isn't an accurate-enough model of water pressure/movement (it's more like compressed air, apparently).

**Comment by HybridDog** [comment]
>The only reason that branch has not been merged to master (permanently, that is :stuck_out_tongue_closed_eyes: ) is because some folks feel it isn't an accurate-enough model of water pressure/movement (it's more like compressed air, apparently).

l think it it's better than the current one, it should be merged.

**Comment by VanessaE** [comment]
the consensus so far is that it is rather worse (even though the code is much better).

**Comment by HybridDog** [comment]
Does the new flow logic make it possible to make water from above flow into a pipe without a pump and if the pipe then leads up the water in the pipes doesn't get higher than the water source's height and if the pipe there is closed (no exit) the water flows only into e.g. the first pipe and compresses the air?

**Comment by VanessaE** [comment]
I never thought to add such features.

At the very least, making water tend to flow downward due to gravity would be pretty easy.  Detecting the level of nearby water sources from which a pipeline is fed, on the other hand, would be far more difficult is it would require adding a simulation of the water's weight, in addition to a more correct simulation of water pressure.
