### ISSUE TITLE
Sand vacuum tubes not working

### ISSUE THREAD

**Issue by Ginger88895** [VanessaE/pipeworks#121]
It's an issue in the abm.

**Comment by LeMagnesium** [comment]
It can be fixed by simply replacing [this line](https://github.com/VanessaE/pipeworks/blob/master/vacuum_tubes.lua#L115) : 

    if node.name == "pipeworks:sand_tube" then

with [this line](https://github.com/MinetestForFun/server-minetestforfun/commit/a296193b919b2015579c41113d925d9a0c6ef7e7#diff-edf5d9b27cd364028bb2ac5dfd9ebabaR115):

    if node.name:find("pipeworks:sand_tube") then

**Comment by Ginger88895** [comment]
however no-one seems going to commit...

**Comment by LeMagnesium** [comment]
There is that PR (#115), but not only it solves the problem, it rewrites the entire mechanism of vacuuming. Someone should fix the code and then review the PR to change the vacuuming system.

**Comment by HybridDog** [comment]
>Someone should fix the code and then review the PR to change the vacuuming system.

The changed mechanism doesn't directly search sand pipes l think, so fixing the current code is only needed if you want to be able to switch back to the current mechanism.

**Comment by LeMagnesium** [comment]
@HybridDog Yes that is what I understood when I read your PR's diff. My point was that either your request should be merged soon or a fix should rapidly be applied onto the vacuum mechanism, because the current system is broken, we know why it is, and we have two ways of fixing it, but still nothing happens.

**Comment by HybridDog** [comment]
You remember me to that other bug where they don't want to fix it:
https://github.com/minetest/minetest/pull/3163

**Comment by asl97** [comment]
Just create your own fork, fix the problem and post it somewhere if they don't want to merge the fix.

When you get more popular/stars than the original/official repo, your fork/repo would become the standard/official repo to look for update (sort of).

[your fork would become searchable too](https://github.com/blog/1381-a-whole-new-code-search)

**Comment by HybridDog** [comment]
@asl97 freeminer merged it

**Comment by asl97** [comment]
freeminer isn't a fork created using the fork button on github so it doesn't really count.

anyway, it's getting off topic.

**Comment by VanessaE** [comment]
fd1318d9e1cd8aea2f11214b644fcc3fe3d6a5dd
