### ISSUE TITLE
problem when a node gets to the end of a tube. Item does not fall to ground

### ISSUE THREAD

**Issue by dkelley810** [VanessaE/pipeworks#127]
says it should - Breaking a tube carrying items simply drops the items onto the ground.
error I get: 

Runtime error from mod 'pipeworks' in callback environment_Step():/usr/share/games/minetest/builtin/game/item.lua:338: attempt to index local 'dropper' (a nil value) 
stack traceback:
 /usr/share/games/minetest/builtin/game/item.lua:338: in function 'item_drop'
 /home/dennis/.minetest/mods/pipeworks/item_transpot.lua:252: in function 'on_step'
 /home/dennis/.minetest/mods/pipeworks/luaenity.lua:347: in function </home/dennis/.minetest/mods/pipeworks.lua:312>
 /usr/share/games/minetest/builtin/game/register.lua:335: in function </usr/share/games/minetest/builtin/game/register.lua:335>

I have Minetest 0.4.13

I have very basic programming skills, any help would be awesome.

**Comment by HybridDog** [comment]
So you dig a tube while it transport item(s) and then it crashes, don't you?

**Comment by dkelley810** [comment]
I have a tube that does not go to a storage box or trash can. I
t is supposed to just drop to the ground right?

**Comment by HybridDog** [comment]
The commit https://github.com/VanessaE/pipeworks/commit/352e23cfb12c00b89e4d2b382b7821555203ae4c?w=1 changed the behaviour fixing a bug with new versions of minetest.
Obviously (there's nothing with player at https://github.com/minetest/minetest/blob/master/builtin/game/item.lua#L338 , there was before https://github.com/minetest/minetest/blob/9675d9e9cb1f951a154d2fcd26fea6fb94632c7d/builtin/game/item.lua#L338) you don't use the newest version of minetest.
Can you update your minetest?

**Comment by dkelley810** [comment]
its says that its version 0.4.13 
I am not using the latest version of Minetest?

**Comment by HybridDog** [comment]
You aren't, the newest one is minetest 0.4.13-dev, 0.4.13 is from 20 august, see https://github.com/minetest/minetest/commit/d44fceac7e1237b00c6431ee1bb5805b602d0dcd.

@VanessaE pipeworks also must work for stable release, doesn't it?

**Comment by VanessaE** [comment]
I don't generally target stable releases when they start to get that old.

@dkelley810, like @HybridDog suggested, you need to update to a development build.  These can be found on the Minetest forum, or you can compile it yourself as well.

**Comment by dkelley810** [comment]
Awesome! That works great!

**Comment by greencopper** [comment]
What has been changed?

**Comment by ssieb** [comment]
minetest_game has been fixed to check for "dropper" being nil before trying to dereference it.
