### ISSUE TITLE
Crash on stable minetest 0.4.13

### ISSUE THREAD

**Issue by adrido** [VanessaE/pipeworks#130]
This crash happens with stable Minetest 0.4.13

For error messages see in Minetest Forum Thread:
https://forum.minetest.net/viewtopic.php?f=11&t=2155&start=500#p202824
https://forum.minetest.net/viewtopic.php?f=11&t=2155&start=500#p205101
https://forum.minetest.net/viewtopic.php?f=11&t=2155&start=500#p205434

blame commits 352e23cfb12c00b89e4d2b382b7821555203ae4c
and 6de437b83d99cdc49dc7899b3bf4fc6f94054d92

In my opinion mods master branch should always work with latest stable Minetest version.
But if `<insert mod authors here>` decides to do something different, this should be at least noted in the [Forum Thread](https://forum.minetest.net/viewtopic.php?t=2155). Also there should be a download available that works with stable Minetest 0.4.13

**Comment by carg0cult** [comment]
This crashed my world on startup when I had placed a quarry with no tube attached. I fixed this by checking out the commit before those two mentioned above. Would be easier for people if branching had been used properly.

**Comment by adrido** [comment]
yes, at most for these people that does not have much experience with git and just hit the download button.

But it seems no one cares about it. :angry:

**Comment by VanessaE** [comment]
I am inactive right now, but I don't target stable Minetest releases once they start to get old, and 0.4.13 is pretty old (going on 6 months now - August 19, 2015).

**Comment by adrido** [comment]
:laughing: If Microsoft (or any other developer) would say this :laughing: 

Its Ok, some days I also does not have much time, but
please update Minetest forum thread and replace the line `Dependencies: Minetest 0.4.11 or later.`
with `Dependencies: Minetest 0.4.14 or later.`

**Comment by HybridDog** [comment]
l think minetest is a special case, other games, e.g. supertux, supertuxkart, frogatto, extremetuxracer etc., need faster computers (supertuxkart) and/or have changes which not everyone likes and can't be disabled (frogatto) after becoming developed.

**Comment by adrido** [comment]
Yes, I fully agree, the only problem is that it should be noted somewhere. If someone uses 0.4.11 and reads in forum thread `Dependencies: Minetest 0.4.11 or later.` he thinks: "Oh great, a mod that works with my minetest version". But he only get frustrated because it always crashes and does not understand why.

**Comment by HybridDog** [comment]
l agree, sadly you can't add collaborators to forum topic editing.

**Comment by VanessaE** [comment]
Ok, fixed the forum topic.
