### ISSUE TITLE
Adding a pipe to a turned on pump causes the pipe to stay full all the time.

### ISSUE THREAD

**Issue by MT-Modder** [VanessaE/pipeworks#78]
![screenshot_41975820](https://cloud.githubusercontent.com/assets/7414772/5499471/443c959c-86fe-11e4-8b47-895395541fe8.png)

To reproduce this loop pipes after a long line of pipes with corners and switch the pump on and off until the pipes stay full even with the pump off. It's kinda hard to reproduce but it's a serious issue. Like this:

![screenshot_42624449](https://cloud.githubusercontent.com/assets/7414772/5499552/e9588940-86ff-11e4-85c4-bf129e2e549f.png)

To fix it you have to dig all the pipes and replace them but eventually it will happen again.

**Comment by MT-Modder** [comment]
It looks like commit https://github.com/VanessaE/pipeworks/commit/5f393d05456ee5b2a721db6c55cd79338cd230c4 didn't completely fix this ;)

**Comment by MT-Modder** [comment]
Yay!!!!!!! Thank you.

**Comment by t4im** [comment]
With pleasure. Though it should still require you replacing any pipes that sorrounded a change (dig or placement) in a running tube system due to missing "source" metadata.

**Comment by MT-Modder** [comment]
Okay thanks for the info. I didn't have any pipes in place because of this bug so that's a non issue for me :smiley:
