### ISSUE TITLE
Pipeworks breaks mesecons pistons

### ISSUE THREAD

**Issue by C1ffisme** [VanessaE/pipeworks#92]
I don't know what happens, but apperently pipeworks puts a table in mesecon.on_mvps_move(). This breaks mesecons, since all the stuff in that table is called as a function, when some of the stuff in there is made a table by pipeworks. I have tried this with and without pipeworks and it seems that pipeworks is the culprit. I'm thinking that somewhere in the code, a function was run and the returned value put into the table, rather than the function being put into the table.

**Comment by t4im** [comment]
Could you please explain a way to reproduce the bug? What would be the expected behavior?
Also if there was a crash, could you please provide us the stacktrace? :-)

**Comment by est31** [comment]
couldn't [find](https://github.com/VanessaE/pipeworks/search?utf8=%E2%9C%93&q=register_on_mvps_move) anything where an non-function is registered into the table.

**Comment by C1ffisme** [comment]
This is the error : (Sorry, too young for pastebin)

17:27:05: ERROR[main]: ServerError: ...mods/minetest-mod-mesecons-master/mesecons_mvps/init.lua:39: attempt to call local 'callback' (a table value)
17:27:05: ERROR[main]: stack traceback:
17:27:05: ERROR[main]: 	...mods/minetest-mod-mesecons-master/mesecons_mvps/init.lua:39: in function 'on_mvps_move'
17:27:05: ERROR[main]: 	...mods/minetest-mod-mesecons-master/mesecons_mvps/init.lua:114: in function 'mvps_push'
17:27:05: ERROR[main]: 	...s/minetest-mod-mesecons-master/mesecons_pistons/init.lua:83: in function 'action_on'
17:27:05: ERROR[main]: 	.../mods/minetest-mod-mesecons-master/mesecons/internal.lua:189: in function <.../mods/minetest-mod-mesecons-master/mesecons/internal.lua:184>
17:27:05: ERROR[main]: 	...ds/minetest-mod-mesecons-master/mesecons/actionqueue.lua:90: in function 'execute'
17:27:05: ERROR[main]: 	...ds/minetest-mod-mesecons-master/mesecons/actionqueue.lua:84: in function <...ds/minetest-mod-mesecons-master/mesecons/actionqueue.lua:61>
17:27:05: ERROR[main]: 	/usr/share/minetest/builtin/game/register.lua:341: in function </usr/share/minetest/builtin/game/register.lua:329>

Note that I am not currently using the latest git version, I will report back when I have downloaded and tested.

**Comment by C1ffisme** [comment]
Tested with the latest git version. It works fine, must just be old version problems. Closing.
